import type { ContractReportEntry, ContractTestReport, ContractViolation, CoverageReport } from "./types.ts";

/**
 * Contract testing report and export (spec §38, §39).
 *
 * ## Secret handling
 *
 * Spec §39 requires that exports contain no secrets. This report is built
 * only from contract *metadata* — operation paths, JSON paths, schema
 * keywords, and expected/actual type descriptions. It deliberately never
 * carries request headers, authorization values, environment variables,
 * cookies, or raw request/response bodies, so there is no field in which a
 * bearer token or API key could travel into an exported file. The M10
 * performance report took the same approach for the same reason, and the
 * shape of these exports follows it.
 *
 * `expected`/`actual` on a violation are the one place a *value* can appear,
 * and they are bounded, type-level descriptions produced by
 * jsonSchemaValidate.ts (`"integer"`, `"one of a, b"`, a truncated literal)
 * — never a header or credential, because credentials are not schema-validated
 * against a contract in the first place.
 */

export function buildContractReport(
  specificationTitle: string,
  openapiVersionString: string,
  entries: ContractReportEntry[],
  coverage: CoverageReport | null,
): ContractTestReport {
  return {
    specificationTitle,
    openapiVersionString,
    generatedAt: new Date().toISOString(),
    totalRequests: entries.length,
    validCount: entries.filter((entry) => entry.valid).length,
    violationCount: entries.reduce((total, entry) => total + entry.violations.length, 0),
    warningCount: entries.reduce((total, entry) => total + entry.warnings.length, 0),
    coverage,
    entries,
  };
}

function violationToJson(violation: ContractViolation): Record<string, unknown> {
  return {
    location: violation.location,
    path: violation.path,
    keyword: violation.keyword,
    expected: violation.expected,
    actual: violation.actual,
    message: violation.message,
    severity: violation.severity,
  };
}

export function contractReportToJson(report: ContractTestReport): string {
  return JSON.stringify(
    {
      specification: report.specificationTitle,
      openapiVersion: report.openapiVersionString,
      generatedAt: report.generatedAt,
      summary: {
        requests: report.totalRequests,
        contractValid: report.validCount,
        contractViolations: report.violationCount,
        warnings: report.warningCount,
        operationCoveragePercent: report.coverage?.operationCoveragePercent ?? null,
        contractTestCoveragePercent: report.coverage?.validationCoveragePercent ?? null,
      },
      coverage: report.coverage
        ? {
            totalOperations: report.coverage.totalOperations,
            coveredByCollection: report.coverage.coveredOperations,
            operationCoveragePercent: report.coverage.operationCoveragePercent,
            validatedOperations: report.coverage.validatedOperations,
            contractTestCoveragePercent: report.coverage.validationCoveragePercent,
            uncovered: report.coverage.uncovered.map((entry) => `${entry.method} ${entry.path}`),
          }
        : null,
      results: report.entries.map((entry) => ({
        request: entry.requestName,
        method: entry.method,
        path: entry.path,
        valid: entry.valid,
        violations: entry.violations.map(violationToJson),
        warnings: entry.warnings.map(violationToJson),
      })),
      note: "Generated by API Lab. Contains contract metadata only — no request headers, credentials, environment values, or response bodies.",
    },
    null,
    2,
  );
}

function csvEscape(value: string | number | boolean): string {
  const text = String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function csvRow(cells: Array<string | number | boolean>): string {
  return cells.map(csvEscape).join(",");
}

/**
 * CSV export. Like the M10 performance export, the file is written as
 * labelled sections rather than pretending a nested report is one flat
 * table.
 */
export function contractReportToCsv(report: ContractTestReport): string {
  const lines: string[] = [];

  lines.push("Section,Metric,Value");
  lines.push(csvRow(["Summary", "Specification", report.specificationTitle]));
  lines.push(csvRow(["Summary", "OpenAPI version", report.openapiVersionString]));
  lines.push(csvRow(["Summary", "Generated at", report.generatedAt]));
  lines.push(csvRow(["Summary", "Requests", report.totalRequests]));
  lines.push(csvRow(["Summary", "Contract valid", report.validCount]));
  lines.push(csvRow(["Summary", "Contract violations", report.violationCount]));
  lines.push(csvRow(["Summary", "Warnings", report.warningCount]));
  if (report.coverage) {
    lines.push(csvRow(["Coverage", "OpenAPI operations", report.coverage.totalOperations]));
    lines.push(csvRow(["Coverage", "Covered by collection", report.coverage.coveredOperations]));
    lines.push(csvRow(["Coverage", "Operation coverage (%)", report.coverage.operationCoveragePercent]));
    lines.push(csvRow(["Coverage", "Validated operations", report.coverage.validatedOperations]));
    lines.push(csvRow(["Coverage", "Contract test coverage (%)", report.coverage.validationCoveragePercent]));
  }

  lines.push("");
  lines.push("Request,Method,Path,Result,Violations,Warnings");
  for (const entry of report.entries) {
    lines.push(
      csvRow([
        entry.requestName,
        entry.method,
        entry.path,
        entry.valid ? "PASS" : "FAIL",
        entry.violations.length,
        entry.warnings.length,
      ]),
    );
  }

  lines.push("");
  lines.push("Request,Severity,Location,Path,Keyword,Expected,Actual,Message");
  for (const entry of report.entries) {
    for (const violation of [...entry.violations, ...entry.warnings]) {
      lines.push(
        csvRow([
          entry.requestName,
          violation.severity,
          violation.location,
          violation.path,
          violation.keyword,
          violation.expected,
          violation.actual,
          violation.message,
        ]),
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

/** The compact summary block shown above the report in the UI (spec §38). */
export function formatContractReportSummary(report: ContractTestReport): string {
  const lines = [
    "Contract Test Result",
    `Specification: ${report.specificationTitle} (OpenAPI ${report.openapiVersionString})`,
    `Requests: ${report.totalRequests}`,
    `Contract valid: ${report.validCount}`,
    `Contract violations: ${report.violationCount}`,
    `Warnings: ${report.warningCount}`,
  ];
  if (report.coverage) {
    lines.push(
      `OpenAPI operations: ${report.coverage.totalOperations}`,
      `Covered by collection: ${report.coverage.coveredOperations} (${report.coverage.operationCoveragePercent}%)`,
      `Validated operations: ${report.coverage.validatedOperations} (${report.coverage.validationCoveragePercent}%)`,
    );
  }
  return lines.join("\n");
}
