import { ERROR_KIND_LABELS } from "./classify.ts";
import { COMPARATOR_LABELS, METRIC_LABELS, METRIC_UNITS } from "./thresholds.ts";
import { PERF_ERROR_KINDS, type PerformanceReport } from "./types.ts";

function round(value: number, digits = 2): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

/**
 * Export (spec §36). Both formats deliberately contain **aggregates only** —
 * summary metrics, status distribution, per-second time series, and
 * threshold results. Individual request records are never exported, because
 * they are never retained in the first place (spec §23): there is no
 * per-request log to leak a URL, header, token, or response body into an
 * exported file.
 */
export function reportToJson(report: PerformanceReport): string {
  const { snapshot } = report;
  return JSON.stringify(
    {
      runId: report.runId,
      status: report.status,
      target: { kind: report.targetKind, name: report.targetName },
      environment: report.environmentName,
      loadModel: report.loadModel,
      virtualUsers: report.virtualUsers,
      configuredDurationSeconds: report.configuredDurationSeconds,
      rampUpSeconds: report.rampUpSeconds,
      startedAt: new Date(report.startedAt).toISOString(),
      durationMs: round(report.durationMs),
      summary: {
        attempted: snapshot.attempted,
        completed: snapshot.completed,
        abortedInFlight: snapshot.aborted,
        successful: snapshot.successful,
        failed: snapshot.failed,
        errorRatePercent: round(snapshot.errorRate * 100),
        requestsPerSecond: round(snapshot.rps),
        successfulRequestsPerSecond: round(snapshot.successfulRps),
        throughputBytesPerSecond: round(snapshot.throughputBytesPerSec),
        latencyMs: {
          min: round(snapshot.latency.min),
          max: round(snapshot.latency.max),
          avg: round(snapshot.latency.avg),
          p50: round(snapshot.latency.p50),
          p90: round(snapshot.latency.p90),
          p95: round(snapshot.latency.p95),
          p99: round(snapshot.latency.p99),
        },
        latencyPercentilesAreEstimates: snapshot.latencySampled,
      },
      statusDistribution: snapshot.statusDistribution,
      errors: snapshot.errors,
      timeSeries: snapshot.timeSeries.map((point) => ({
        second: point.second,
        requests: point.requests,
        errors: point.errors,
        avgLatencyMs: round(point.avgLatencyMs),
        p95LatencyMs: round(point.p95LatencyMs),
      })),
      thresholds: report.thresholdResults.map((result) => ({
        metric: result.threshold.metric,
        comparator: result.threshold.comparator,
        expected: result.threshold.value,
        actual: round(result.actual),
        passed: result.passed,
      })),
      errorMessage: report.errorMessage,
      note: "Generated by API Lab. Load was produced by a single local worker process — these figures are not equivalent to distributed production load-test results.",
    },
    null,
    2,
  );
}

function csvEscape(value: string | number): string {
  const text = String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function csvRow(cells: Array<string | number>): string {
  return cells.map(csvEscape).join(",");
}

/**
 * CSV export. A performance report is not a single flat table, so the file
 * is written as clearly-labelled sections (Summary / Status distribution /
 * Errors / Time series / Thresholds) separated by blank lines — readable in
 * a spreadsheet without pretending the data is something it isn't.
 */
export function reportToCsv(report: PerformanceReport): string {
  const { snapshot } = report;
  const lines: string[] = [];

  lines.push("Section,Metric,Value");
  lines.push(csvRow(["Summary", "Run ID", report.runId]));
  lines.push(csvRow(["Summary", "Status", report.status]));
  lines.push(csvRow(["Summary", "Target", report.targetName]));
  lines.push(csvRow(["Summary", "Environment", report.environmentName ?? "None"]));
  lines.push(csvRow(["Summary", "Load model", report.loadModel]));
  lines.push(csvRow(["Summary", "Virtual users", report.virtualUsers]));
  lines.push(csvRow(["Summary", "Ramp-up (s)", report.rampUpSeconds]));
  lines.push(csvRow(["Summary", "Elapsed (s)", round(report.durationMs / 1000)]));
  lines.push(csvRow(["Summary", "Attempted requests", snapshot.attempted]));
  lines.push(csvRow(["Summary", "Completed requests", snapshot.completed]));
  lines.push(csvRow(["Summary", "Aborted in-flight requests", snapshot.aborted]));
  lines.push(csvRow(["Summary", "Successful requests", snapshot.successful]));
  lines.push(csvRow(["Summary", "Failed requests", snapshot.failed]));
  lines.push(csvRow(["Summary", "Error rate (%)", round(snapshot.errorRate * 100)]));
  lines.push(csvRow(["Summary", "Completed requests/sec", round(snapshot.rps)]));
  lines.push(csvRow(["Summary", "Successful requests/sec", round(snapshot.successfulRps)]));
  lines.push(csvRow(["Summary", "Throughput (bytes/sec)", round(snapshot.throughputBytesPerSec)]));
  lines.push(csvRow(["Summary", "Min latency (ms)", round(snapshot.latency.min)]));
  lines.push(csvRow(["Summary", "Average latency (ms)", round(snapshot.latency.avg)]));
  lines.push(csvRow(["Summary", "P50 latency (ms)", round(snapshot.latency.p50)]));
  lines.push(csvRow(["Summary", "P90 latency (ms)", round(snapshot.latency.p90)]));
  lines.push(csvRow(["Summary", "P95 latency (ms)", round(snapshot.latency.p95)]));
  lines.push(csvRow(["Summary", "P99 latency (ms)", round(snapshot.latency.p99)]));
  lines.push(csvRow(["Summary", "Max latency (ms)", round(snapshot.latency.max)]));
  lines.push(csvRow(["Summary", "Percentiles are estimates", snapshot.latencySampled ? "yes" : "no"]));

  lines.push("");
  lines.push("Status code,Count");
  for (const entry of snapshot.statusDistribution) {
    lines.push(csvRow([entry.status, entry.count]));
  }

  lines.push("");
  lines.push("Error kind,Count");
  for (const kind of PERF_ERROR_KINDS) {
    lines.push(csvRow([ERROR_KIND_LABELS[kind], snapshot.errors[kind]]));
  }

  lines.push("");
  lines.push("Second,Requests,Errors,Avg latency (ms),P95 latency (ms)");
  for (const point of snapshot.timeSeries) {
    lines.push(csvRow([point.second, point.requests, point.errors, round(point.avgLatencyMs), round(point.p95LatencyMs)]));
  }

  lines.push("");
  lines.push("Threshold,Expected,Actual,Result");
  for (const result of report.thresholdResults) {
    const unit = METRIC_UNITS[result.threshold.metric];
    lines.push(
      csvRow([
        `${METRIC_LABELS[result.threshold.metric]} ${COMPARATOR_LABELS[result.threshold.comparator]} ${result.threshold.value}${unit}`,
        `${result.threshold.value}${unit}`,
        `${round(result.actual)}${unit}`,
        result.passed ? "PASS" : "FAIL",
      ]),
    );
  }

  return `${lines.join("\n")}\n`;
}

/** The compact text block shown in the UI's report header (spec §33). */
export function formatReportSummary(report: PerformanceReport): string {
  const { snapshot } = report;
  return [
    "Performance Test Result",
    `Status: ${report.status.toUpperCase()}`,
    `Duration: ${round(report.durationMs / 1000, 1)}s`,
    `Virtual Users: ${report.virtualUsers}`,
    `Requests: ${snapshot.completed.toLocaleString()}`,
    `RPS: ${round(snapshot.rps, 1)}`,
    `Average: ${round(snapshot.latency.avg)}ms`,
    `P50: ${round(snapshot.latency.p50)}ms`,
    `P90: ${round(snapshot.latency.p90)}ms`,
    `P95: ${round(snapshot.latency.p95)}ms`,
    `P99: ${round(snapshot.latency.p99)}ms`,
    `Errors: ${round(snapshot.errorRate * 100)}%`,
  ].join("\n");
}
